FOR LATER

* Adam tests should use a full package

  Adam.py should be adam/part1.py and adam/part2.py or something. A bit more realistic.

* TODO Re-enable comparison operator replacement "special rules"

* TODO Exclusion should be done via interceptors

    Rather than exclude modules at init time, we should exclude them using the interceptor system.

* TODO Remove test-runner plugins from pypi?

* TODO Add "command line" command for producing a command line
  Don't forget to update _print_item to use this.
 
* TODO celery worker must limit self to one process!

  We can't let celery start up multiple "threads" else it'll collide with itself.

* TODO Consider alternatives to celery

  rq: https://github.com/rq/rq

 * TODO Verify that celery tests work

 * TODO Consider using interceptors to skip operator replacements that we want to avoid.

 * TODO Each operator should provide a series of "samples" that can be used in testing.
  
* TODO Can we use value-added to insert help from each command into the rst docs?